version: "3.7"

services:
  pony:
    build:
      context: ./
      target: localdev
    command:
      - "npm"
      - "run"
      - "dev"
    ports:
      - 10001:10001
    volumes:
      - ./:/app:rw
